# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-26 08:56
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('other_pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='country',
            field=django_countries.fields.CountryField(default='BE', max_length=2, verbose_name='location (land)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='website',
            field=models.URLField(blank=True, verbose_name='website link'),
        ),
    ]
