# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-26 09:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other_pages', '0004_auto_20170526_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='startdatum'),
        ),
    ]
