# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-22 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_update_email_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='language',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
