# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-29 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0012_auto_20170429_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='original',
            field=models.ImageField(max_length=255, upload_to='images/products/%Y/%m/', verbose_name='Original'),
        ),
    ]
