# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-02 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0013_auto_20170429_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_nl',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_fr',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_nl',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='Name'),
        ),
    ]
